spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: file:///Users/ariel/workspace/_learning/web/java/udemy-master-microservices-with-spring-boot-and-spring-cloud-in28minutes/section-03-microservices-with-spring-cloud/git-localconfig-repo
server:
  port: 8888
